motd:
  description: "&6&lDashNetwork &6&l»&7 [1.8-{$VERSION_HIGHEST}]"
  software: "Requires 1.8-{$VERSION_HIGHEST}"
  hover: [
    "&f          &6&n&lDashNetwork",
    "&6&lMinecraft &7play.dashnetwork.xyz",
    "&6&lDiscord &7discord.gg/3RDsNEE"
  ]
sql:
  host: "127.0.0.1"
  database: "s1_celest"
  username: "admin"
  password: "password"